# .github/workflows/bump_documentation.yml

name: Deploy API Documentation to Bump.sh

# Run this workflow every time a change is pushed to the main branch
on:
  push:
    branches:
      - main  # Or 'master', depending on your default branch name

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Deploy the documentation using the Bump.sh CLI Action
      # This action finds your openapi.json file and sends it to Bump.sh
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          # The slug for your documentation (the one you set up in the form)
          doc: paddy-disease-api
          
          # The token and ID are securely stored as GitHub secrets
          token: ${{ secrets.BUMP_TOKEN }}
          id: ${{ secrets.BUMP_ID }}
          
          # The file containing your API definition. 
          # FastAPI automatically creates this at the /openapi.json endpoint.
          # We use the public URL of your deployed app.
          file: https://paddy-disease-api.vercel.app/openapi.json
